language: rust
sudo: false
git:
  submodules: false

matrix:
  include:
    - rust: 1.21.0
    - rust: stable
    - os: osx
      rust: stable
      before_install:
        - export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
        - export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
    - rust: beta
    - rust: nightly

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps
        - cargo doc --manifest-path=git2-curl/Cargo.toml --no-deps
        - cargo doc --manifest-path=libgit2-sys/Cargo.toml --no-deps
      after_success:
        - travis-cargo --only nightly doc-upload

script:
  - git submodule update --init
  - cargo test --no-default-features
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml --release
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo test --features unstable;
      cargo test --manifest-path git2-curl/Cargo.toml;
    fi

env:
  global:
    secure: "SVk5cv4VnBQAoaBXt9pIHk+FQ7Z58zT5EaPo7Ac81LltKztwHovhN/R1otKzgrAJqFsZ/nKR4cGyQGbYtfVJcsqweQVM75LI6Oh6lYyEdfX211ZI3SWQ50JO93CmwLtanC5UpECdXvJLCgXrHGJXuL1oi7hySGy47/yQlKH6eaM="

notifications:
  email:
    on_success: never

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
