[package]
name = "libgit2-sys"
version = "0.7.6"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "git2"
build = "build.rs"
repository = "https://github.com/alexcrichton/git2-rs"
license = "MIT/Apache-2.0"
description = "Native bindings to the libgit2 library"
exclude = [
    "libgit2/tests/*",
]

[lib]
name = "libgit2_sys"
path = "lib.rs"

[dependencies]
curl-sys = { version = "0.4.6", optional = true }
libc = "0.2"
libssh2-sys = { version = "0.2.8", optional = true }
libz-sys = "1.0.18"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1.24"
cc = "1.0"

[target.'cfg(unix)'.dependencies]
openssl-sys = { version = "0.9", optional = true }

[features]
ssh = ["libssh2-sys"]
https = ["openssl-sys"]
curl = ["curl-sys"]
