[package]

name = "libgit2-sys"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "git2"
build = "build.rs"

[lib]
  name = "libgit2-sys"
  path = "lib.rs"

[dependencies.libssh2-sys]
  git = "https://github.com/alexcrichton/ssh2-rs"
  branch = "build-cmd"

[build-dependencies.pkg-config]
  git = "https://github.com/alexcrichton/pkg-config-rs"

[target.i686-apple-darwin.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.x86_64-apple-darwin.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.i686-unknown-linux-gnu.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.x86_64-unknown-linux-gnu.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.i686-unknown-freebsd.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
[target.x86_64-unknown-freebsd.dependencies.openssl-sys]
  git = "https://github.com/alexcrichton/openssl-sys"
