[package]

name = "libgit2-sys"
version = "0.4.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "git2"
build = "build.rs"
repository = "https://github.com/alexcrichton/git2-rs"
license = "MIT/Apache-2.0"
description = "Native bindings to the libgit2 library"

[lib]
name = "libgit2_sys"
path = "lib.rs"

[dependencies]
libssh2-sys = { version = ">= 0", optional = true }
libc = "0.2"
libz-sys = ">= 0"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1.2"
gcc = "0.3"

[target."cfg(all(unix, not(target_os = \"macos\")))".dependencies]
openssl-sys = "0.7.0"

[target.i686-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.i586-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = "0.7.0"
[target.aarch64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.powerpc64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.powerpc64le-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.arm-unknown-linux-gnueabihf.dependencies]
openssl-sys = "0.7.0"
[target.armv7-unknown-linux-gnueabihf.dependencies]
openssl-sys = "0.7.0"
[target.i686-unknown-freebsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-freebsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-bitrig.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-openbsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-dragonfly.dependencies]
openssl-sys = "0.7.0"

[features]
ssh = ["libssh2-sys"]
https = []
