[package]

name = "libgit2-sys"
version = "0.6.12"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "git2"
build = "build.rs"
repository = "https://github.com/alexcrichton/git2-rs"
license = "MIT/Apache-2.0"
description = "Native bindings to the libgit2 library"

[lib]
name = "libgit2_sys"
path = "lib.rs"

[dependencies]
curl-sys = { version = "0.3.12", optional = true }
libc = "0.2"
libssh2-sys = { version = "0.2.4", optional = true }
libz-sys = ">= 0"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1.2"
gcc = "0.3"

[target."cfg(all(unix, not(target_os = \"macos\")))".dependencies]
openssl-sys = { version = "0.9", optional = true }

[features]
ssh = ["libssh2-sys"]
https = ["openssl-sys"]
curl = ["curl-sys"]
