[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libgit2-sys = { path = "../libgit2-sys", features = ['https', 'ssh'] }
libc = "0.2"

[build-dependencies]
ctest = "0.2"
